import * as g                           from '../types/genetics'

export const en_r: g.Ribosome[] = [
    {
        institute   : "en",
        code        : "CMSTRIP",
        type        : "comic",
		level       : "B1",
		title       : "Commit Strip for Developers",
        avatar      : "https://prashantsani.com/spider/content/images/size/w2000/2017/04/commitStrip-Rise-of-the-coders-English-Hardcover.jpg",
        source      : "commitstrip.com",
        contains    : "∞",
        readMode    : "start"
    },
    {
        institute   : "en",
        code        : "BBCSHSP",
        type        : "audio",
		level       : "B1",
		title       : "Shakespeare Speaks",
        avatar      : "https://www.open.edu/openlearn/sites/www.open.edu.openlearn/files/styles/ole_ng_content_style_featured/public/ole_images/screen-feat.png",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCCHCO",
        type        : "audio",
		level       : "B2",
		title       : "A Christmas Carol",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p07xny96.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCALIC",
        type        : "audio",
		level       : "B2",
		title       : "Alice in Wonder-\nland",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p02kvlvk.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCGVTR",
        type        : "audio",
		level       : "B2",
		title       : "Gulliver's Travels",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p033wm70.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCITBE",
        type        : "audio",
		level       : "B2",
		title       : "The Importance of Being Earnest",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p06t92r9.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCINNM",
        type        : "audio",
		level       : "C1",
		title       : "Jamaica Inn",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p08hqrpl.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCRACE",
        type        : "audio",
		level       : "C1",
		title       : "Race",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p0252gs9.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "STRYOA1",
        type        : "video",
		level       : "A1",
		title       : "Storyline Online\nA1",
        avatar      : "https://i0.wp.com/speechisbeautiful.com/wp-content/uploads/2016/03/storylineonline.png",
        source      : "storylineonline.net",
        contains    : null,
        readMode    : "end",
        private     : false,
    },
    {
        institute   : "en",
        code        : "STRYOA2",
        type        : "video",
		level       : "A2",
		title       : "Storyline Online\nA2",
        avatar      : "https://i0.wp.com/speechisbeautiful.com/wp-content/uploads/2016/03/storylineonline.png",
        source      : "storylineonline.net",
        contains    : null,
        readMode    : "end",
        private     : false,
    },
    {
        institute   : "en",
        code        : "STRYOB1",
        type        : "video",
		level       : "B1",
		title       : "Storyline Online\nB1",
        avatar      : "https://i0.wp.com/speechisbeautiful.com/wp-content/uploads/2016/03/storylineonline.png",
        source      : "storylineonline.net",
        contains    : null,
        readMode    : "end",
        private     : false,
    },
    {
        institute   : "en",
        code        : "STRYOB2",
        type        : "video",
		level       : "B2",
		title       : "Storyline Online\nB2",
        avatar      : "https://i0.wp.com/speechisbeautiful.com/wp-content/uploads/2016/03/storylineonline.png",
        source      : "storylineonline.net",
        contains    : null,
        readMode    : "end",
        private     : false,
    },
    {
        institute   : "en",
        code        : "INTSDAY",
        type        : "audio",
		level       : "C1",
		title       : "Interesting\nThing of\nthe Day",
        avatar      : "https://www.kickassfacts.com/wp-content/uploads/2017/01/fact-of-the-day.jpg",
        source      : "itotd.com",
        contains    : null,
        readMode    : "start",
        private     : true,
    },
    {
        institute   : "en",
        code        : "EASYRED",
        type        : "audio",
        level       : "A2",
        title       : "Easy\nReading",
        avatar      : "https://www.gse.harvard.edu/sites/default/files//styles/landscape__1000x500/public/banner/Comics_1500x750.jpg",
        source      : "LingQ",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "EATGOUT",
        type        : "audio",
		level       : "A2",
		title       : "Eating\nOut",
        avatar      : "https://image.freepik.com/free-vector/people-eating-out-public-place-sitting-outdoors_82574-11144.jpg",
        source      : "LingQ",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "ENGSTRY",
        type        : "audio",
		level       : "A2",
		title       : "English\nStories",
        avatar      : "https://image.shutterstock.com/image-vector/cartoon-sunrise-nature-landscape-mountains-260nw-1015778155.jpg",
        source      : "LingQ",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "LTLPRNC",
        type        : "audio",
		level       : "B1",
		title       : "The\nLittle\nPrince",
        avatar      : "https://static.lingq.com/media/resources/collections/images/2016/08/05/2af63de478_OXQdW5t.jpg",
        source      : "LingQ",
        contains    : null,
        readMode    : "start",
        private     : false,
    },

]