import * as g                           from '../types/genetics'

export const en_r: g.Ribosome[] = [
    {
        institute   : "en",
        code        : "CMSTRIP",
        type        : "comic",
		level       : "B1",
		title       : "Commit Strip for Developers",
        avatar      : "https://prashantsani.com/spider/content/images/size/w2000/2017/04/commitStrip-Rise-of-the-coders-English-Hardcover.jpg",
        source      : "commitstrip.com",
        contains    : "∞",
        readMode    : "start"
    },
    {
        institute   : "en",
        code        : "BBCSHSP",
        type        : "audio",
		level       : "B1",
		title       : "Shakespeare Speaks",
        avatar      : "https://www.open.edu/openlearn/sites/www.open.edu.openlearn/files/styles/ole_ng_content_style_featured/public/ole_images/screen-feat.png",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCCHCO",
        type        : "audio",
		level       : "B2",
		title       : "A Christmas Carol",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p07xny96.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCALIC",
        type        : "audio",
		level       : "B2",
		title       : "Alice in Wonder-\nland",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p02kvlvk.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCGVTR",
        type        : "audio",
		level       : "B2",
		title       : "Gulliver's Travels",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p033wm70.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCITBE",
        type        : "audio",
		level       : "B2",
		title       : "The Importance of Being Earnest",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p06t92r9.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCINNM",
        type        : "audio",
		level       : "C1",
		title       : "Jamaica Inn",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p08hqrpl.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCRACE",
        type        : "audio",
		level       : "C1",
		title       : "Race",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p0252gs9.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "ELLOLV2",
        type        : "audio",
		level       : "A1",
		title       : "25\nSimple Dialogues",
        avatar      : "https://cdn.pixabay.com/photo/2019/05/22/22/28/brainstorm-4222728_960_720.jpg",
        source      : "elllo.org",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "STRYOA1",
        type        : "video",
		level       : "A1",
		title       : "Storyline Online\nA1",
        avatar      : "https://i0.wp.com/speechisbeautiful.com/wp-content/uploads/2016/03/storylineonline.png",
        source      : "storylineonline.net",
        contains    : null,
        readMode    : "end",
        private     : false,
    },
    {
        institute   : "en",
        code        : "STRYOA2",
        type        : "video",
		level       : "A2",
		title       : "Storyline Online\nA2",
        avatar      : "https://i0.wp.com/speechisbeautiful.com/wp-content/uploads/2016/03/storylineonline.png",
        source      : "storylineonline.net",
        contains    : null,
        readMode    : "end",
        private     : false,
    },
    {
        institute   : "en",
        code        : "STRYOB1",
        type        : "video",
		level       : "B1",
		title       : "Storyline Online\nB1",
        avatar      : "https://i0.wp.com/speechisbeautiful.com/wp-content/uploads/2016/03/storylineonline.png",
        source      : "storylineonline.net",
        contains    : null,
        readMode    : "end",
        private     : false,
    },
    {
        institute   : "en",
        code        : "STRYOB2",
        type        : "video",
		level       : "B2",
		title       : "Storyline Online\nB2",
        avatar      : "https://i0.wp.com/speechisbeautiful.com/wp-content/uploads/2016/03/storylineonline.png",
        source      : "storylineonline.net",
        contains    : null,
        readMode    : "end",
        private     : false,
    },
    {
        institute   : "en",
        code        : "INTSDAY",
        type        : "audio",
		level       : "C1",
		title       : "Interesting\nThing of\nthe Day",
        avatar      : "https://www.kickassfacts.com/wp-content/uploads/2017/01/fact-of-the-day.jpg",
        source      : "itotd.com",
        contains    : null,
        readMode    : "start",
        private     : true,
    },
    {
        institute   : "en",
        code        : "VOASTRY",
        type        : "audio",
		level       : "B1",
		title       : "American Stories",
        avatar      : "https://cdn.pixabay.com/photo/2019/05/14/21/50/storytelling-4203628__340.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOAPRMS",
        type        : "audio",
		level       : "B1",
		title       : "A Princess of Mars",
        avatar      : "https://4.bp.blogspot.com/-198vAkdju2E/V9hcNtX3l1I/AAAAAAABaI4/BtQnCf2rgrAhhgUh7qs5Si-V9_kOkkzGACLcB/w1200-h630-p-k-no-nu/A%2BPrincess%2Bof%2BMars%2Bby%2BMatt%2BTaylor.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOABENC",
        type        : "audio",
		level       : "B1",
		title       : "Benito Cereno",
        avatar      : "https://cdn.pixabay.com/photo/2016/10/18/07/30/ship-1749467_960_720.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOAWISN",
        type        : "audio",
		level       : "B1",
		title       : "William Wilson",
        avatar      : "http://moellerlit.weebly.com/uploads/1/0/2/4/10248653/533359_orig.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOAMURM",
        type        : "audio",
		level       : "B1",
		title       : "The Murders in the Rue Morgue",
        avatar      : "http://minsthorpe.cc/wp-content/uploads/2015/04/ruemorgue-img.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },

    
]