import * as g                           from '../types/genetics'

export const DNA: g.gene[] = [
	{
		"title"		: "Tell me about your day?",
		"text"		: "Sarah: John, tell me about your day. What time do you wake-up?\nJohn: Well, let's see. Some days I wake up early. Maybe about 6 o'clock. Yeah, sometimes I wake up at 6 o'clock.\nWhen I get up early, I like to get ready for the day, take a shower and have breakfast. But other days, I don't like getting up early. Maybe I'll sleep in until 10:00 or 11:00.\nSarah: Wow.\nJohn: Yeah. I like sleeping in late. So sometimes, I wake up at 11:00. On those days, if I know I won't wake up until 11:00, I'll take a shower the night before, before I go to bed. How about you, Sarah? When do you usually wake up?\nSarah: Well, I like everyday to be the same. So I wake up everyday at 8 o'clock.\nJohn: 8:00.\nSarah: 8:00. And I always do the same thing. First, I make coffee right away. Then I wake up my kids and we have breakfast together at about 8:30.\nJohn: Really?\nSarah: Yes. We usually have something easy like bread and yogurt and fruit.\nJohn: I like to have coffee every morning whether I wake up at 6:00 or at 10:00. I'm still going to have coffee. But I often skip breakfast. Do you always eat breakfast everyday?\nSarah: Yes. If I don't eat breakfast, I'm so hungry. What about lunch? What time do you have lunch?\nJohn: Lunch is the same everyday for me. I always eat lunch at 12:30 PM. So whenever I wake up, I do some things and then I always have lunch at 12:30 PM, just half past noon. And I always have a simple lunch. Maybe some soup or spaghetti or a sandwich. Something light, and it's always at half past noon. What time do you eat lunch?\nSarah: That's interesting. I have breakfast at the same time everyday but lunch is always at a different time.\nJohn: Really?\nSarah: Because I'm busy in the morning. I go out, maybe I go shopping. Sometimes, I clean the house. So I might have lunch at 11 o'clock or 12 o'clock. Sometimes as late as 2:30.\nJohn: Oh, that's getting late.\nSarah: Yes. But it's always easy lunch like you. Maybe crackers and cheese or a sandwich or a baked potato.\nJohn: I see.",
		"avatarURL"	: "https://i.vimeocdn.com/video/697171272.jpg?mw=1300&mh=731",
		"mediaURL"	: "https://vod-progressive.akamaized.net/exp=1607601341~acl=%2A%2F987971631.mp4%2A~hmac=1dc08573541fe87e000115d65acfcbeb704c099246d8fc007aeb2fc712558336/vimeo-prod-skyfire-std-us/01/3361/10/266809870/987971631.mp4?download=1&filename=Beginner+%231+Tell+me+about+your+day%3F.mp4"
	},
	{
		"title"		: "When do you eat dinner?",
		"text"		: "John: Do you always have dinner at a different time, too?\nSarah: No. I almost always eat dinner around 6 o'clock. How about you? When do you eat dinner?\nJohn: My dinner time varies a lot just like my breakfast. So maybe I eat dinner later than most people. I think I would have dinner at 7:00 PM at the earliest. But sometimes, I will have dinner as late as 9 o'clock at night.\nSarah: Really?\nJohn: Yeah. I don't mind it. I really like cooking so, if I'm cooking a short thing, I'll have dinner earlier. But I don't mind if it takes two hours to cook something really good, I'll eat later at night.\nSarah: Wow. Can you tell me about your work routine? What time do you usually go to work?\nJohn: See, my work schedule is different everyday. That's why I wake up at a different time everyday. Maybe on – for example, some weeks on Monday, Wednesday and Thursday, I start work at 7:00. But on Thursday and Friday, I don't start work until 11:30.\nSarah: Ah.\nJohn: How about you? Do you have a different work time sometimes?\nSarah: Well, right now, I'm on maternity leave. So I stay home and take care of my new baby.\nJohn: Oh, congratulations.\nSarah: Thank you. I try to work at home a little bit everyday though. If the kids are sleeping or they're playing quietly, I try to do some work. Maybe around 2 o'clock, I can usually get some work done because the kids are sleeping.\nJohn: Oh, if you don't start getting some work done until 2 o'clock in the afternoon, you must be very busy every morning.\nSarah: Yeah. I usually go to the grocery store. Sometimes I take the kids to the park around 10:00 in the morning. I often do the laundry or wash the dishes, and then as soon as the dishes are washed, it's time to make lunch. So I'm busy all day.\nJohn: I see. So that's why your lunch time can change so much.\nSarah: Yeah.\nJohn: Oh, it sounds like a busy day.",
		"avatarURL"	: "https://i.vimeocdn.com/video/697171274.jpg?mw=700&mh=394",
		"mediaURL"	: "https://vod-progressive.akamaized.net/exp=1607601361~acl=%2A%2F987971643.mp4%2A~hmac=10be259b5d57fbfa3edd2750475b2ee6bf3ea71e6194f47e2e3c7545485cf79e/vimeo-prod-skyfire-std-us/01/3361/10/266809880/987971643.mp4?download=1&filename=Beginner+%2302+What+do+you+do+at+night%3F.mp4"
	},
	{
		"title"		: "Do you cook much?",
		"text"		: "Daniel: So Hana, tell me, do you cook much?\nHana: Yes, I always cook. I often cook with my roommate, and we always make Chinese of Japanese food. How about you?\nDaniel: Well, I don’t really cook that often. I’m really busy during the week. So, I always just get something at the shop and get that. But, during the weekends, I always cook during the weekends because I really like making food. That’s what I do.\nHana: So, do you ever eat out?\nDaniel: Only occasionally, because I’m really busy during the week, and I prefer cooking, so not really often. I don’t go out really often to eat. Whenever I’m tired, and I don’t have time to cook during the week, I go and eat out with a friend, so! And you?\nHana: Well, I always , so I normally go and eat out during the weekend with my friends or family.",
		"avatarURL"	: "https://i.vimeocdn.com/video/697171281.jpg?mw=700&mh=394",
		"mediaURL"	: "https://vod-progressive.akamaized.net/exp=1607602034~acl=%2A%2F987971694.mp4%2A~hmac=6574adaf11ae1d98ae412a554c71cb7b2e9e4a120b2c6dff4f0750631f6c8184/vimeo-prod-skyfire-std-us/01/3361/10/266809882/987971694.mp4?download=1&filename=Beginner+%2303+Do+you+cook%3F.mp4"
	},
	{
		"title"		: "Do you eat takeaway?",
		"text"		: "Daniel: So do you ever buy take-away?\nHana: No, I never. Normally when I go out to eat, I like to sit and enjoy my food. How about you?\nDaniel: Well, that's really nice. Of course, I do like to sit and enjoy my food, but I have to admit that occasionally I have to buy take-away, especially when I'm coming late from work, and I'm driving. I'm so hungry that, most of the time, I don't really make it home, so I have to buy something on my way, and that's a shame, so that's the way it is.\nAnd do you usually have people over for dinner?\nHana: Yes, I sometimes do. I really like cooking so occasionally I invite my friends over and cook for them or we all cook together. How about you?\nDaniel: Not really. I do love cooking, but the problem is my place is really small, so even though I want to invite my friends. I never do it, because my place would only fit one or two people. So unfortunately, I never have my friends over for dinner.",
		"avatarURL"	: "https://i.vimeocdn.com/video/697171560.jpg?mw=700&mh=394",
		"mediaURL"	: "https://vod-progressive.akamaized.net/exp=1607602095~acl=%2A%2F987972779.mp4%2A~hmac=f1b69ef2a3e61f915700c3718b44563e5b77457e7ba0b81475cafb3fa5a28173/vimeo-prod-skyfire-std-us/01/3362/10/266810125/987972779.mp4?download=1&filename=Beginner+%2304+Do+you+eat+out+much%3F.mp4"
	},
	{
		"title"		: "Tell me about your Town!",
		"text"		: "John: So Sarah, what can you tell me about your hometown?\nSarah: My hometown. Well, my hometown is called Eau Claire, Wisconsin. And it's a really great city.\nThere are about 80,000 people. There are lots of things to do. There are three movie theatres. I love to watch movies.\nJohn: Me too.\nSarah: There's lots of shopping. You can find anything you want there. There are a lot of malls and stores.\nJohn: Are there many restaurants?\nSarah: Yes. The thing I like is you can eat any type of food. There are Chinese restaurants and Korean restaurants, Italian restaurants. There is a big variety of restaurants, and they're all good.\nJohn: That sounds great. What about parks? Are there many places to see nature in your town?\nSarah: Yes. We have a lot of rivers, and lakes and hills. My hometown has four seasons. So in summer, it's great because there are lots of lakes to swim in, lots of forests to play in. In winter, there is a lot of snow. So you can go ice skating or ice fishing or even skiing.\nJohn: Wow. That sounds really fun.\nSarah: Yeah. It's a really nice city. It's also really safe. There are lots of nice people there.\nJohn: Good. Is there much to do at night?\nSarah: Well, maybe, maybe not. There's not many things to do at night. There aren't any nightclubs. There aren't many bars. So actually, maybe there isn't much night life.\nJohn: That's okay. It sounds like a nice place to have a family.\nSarah: Yeah. It is. It's a great place to have a family. There's lots of good schools and libraries.",
		"avatarURL"	: "https://i.vimeocdn.com/video/697171571.jpg?mw=700&mh=394",
		"mediaURL"	: "https://vod-progressive.akamaized.net/exp=1607602147~acl=%2A%2F987972768.mp4%2A~hmac=47c7f032ada023771c912f21cf907c2e3c53aa22371114fe3520a3ee03a03443/vimeo-prod-skyfire-std-us/01/3362/10/266810131/987972768.mp4?download=1&filename=Beginner+%2305+Sarah%27s+Hometown.mp4"
	},
	{
		"title"		: "What about your town?",
		"text"		: "Sarah: So John, where are you from?\nJohn: My hometown is very small. It's a little town in the countryside, in Wisconsin. There are only 5,000 people there.\nSarah: Wow. There aren't very many people.\nJohn: No, it's very small. There aren't very many businesses. There isn't a shopping mall. There are a lot of grocery stores. And there are a lot of gas stations. But there isn't much to do there.\nSarah: Oh really? Are there any movie theaters?\nJohn: Well, there is one movie theater. So that's a nice thing to do. In fact, there are many screens in the theater. There are eight different movies showing.\nSarah: How about at night? What's fun to do – how about at night? Is there very much night life?\nJohn: Yeah, there is not so much. But there is a bowling alley. It's fun to go bowling with friends. There's a bowling alley and the movie theater. There is one restaurant where you can go for tacos and burritos. And there's one more restaurant for pizza and spaghetti.\nBut during the daytime, you can go to the park. There's a river that goes through the town. So in the middle of town, there's a river. And there's a park that goes along both sides of the river. And at the park, there is a tennis court and a disc golf course.\nSarah: Disc golf?\nJohn: Yeah. I like to play disc golf with my friends. It's really fun. And after we finish playing disc golf, we usually go to the pizza restaurant.\nSarah: Oh, I see. How about schools? Are there very many schools?\nJohn: Let's see. No, there aren't very many. There is only one elementary school, one junior high school and one high school. That's it.\nSarah: Interesting.\nJohn: Yeah. There aren't very many schools but the town doesn't need more schools because there aren't very many people there.\nSarah: I see. Are there any mountains?\nJohn: No. The whole area is very flat. There are no mountains but there are a lot of trees. In fact, there are trees on my town's sign because my town is famous for all the trees on every street.\nSarah: Oh wow. It sounds like a great city.",
		"avatarURL"	: "https://i.vimeocdn.com/video/697171577.jpg?mw=700&mh=394",
		"mediaURL"	: "https://vod-progressive.akamaized.net/exp=1607602214~acl=%2A%2F987972831.mp4%2A~hmac=2472af18cd69f73065858eb8cdd34faada4eae191fe2b50db1bfd7c7acfa6327/vimeo-prod-skyfire-std-us/01/3362/10/266810136/987972831.mp4?download=1&filename=Beginner+%2306+John%27s+hometown.mp4"
	},
	{
		"title"		: "His Weekend",
		"text"		: "Hana: Hello, how are you?\nDaniel: I'm good thanks. How are you?\nHana: I'm good. So what are you going to do this weekend?\nDaniel: Well, on Saturday I think I'm going to go to the gym because I haven't been there for awhile. And then I think I need to clean my house because I didn't have time during the week, and it is a bit messy now. And in the evening, I think I'm going to have dinner with my friends.\nHana: Are you going somewhere after dinner?\nDaniel: I don't think so. I really want to spend this weekend in a really relaxed way, so I don't think I'm going anywhere after dinner.\nHana: I see. How about Sunday?\nDaniel: Well, Sunday, I'm not going to do anything in the morning. I really want to take - you know - a rest, and then I'm going to have lunch with my family cause I haven't seen them for awhile, and then in the afternoon, there's this movie I really want to see, so I'm going to the cinema with my friends.",
		"avatarURL"	: "https://i.vimeocdn.com/video/697171779.jpg?mw=700&mh=394",
		"mediaURL"	: "https://vod-progressive.akamaized.net/exp=1607602303~acl=%2A%2F987973643.mp4%2A~hmac=d00cc0bec666f83202b9999ac3c6d5c50884e1b6c9c669192865eafc93754ff8/vimeo-prod-skyfire-std-us/01/3362/10/266810314/987973643.mp4?download=1&filename=Beginner+%2307+The+Weekend.mp4"
	},
	{
		"title"		: "Future Plans",
		"text"		: "Daniel: Hey, Hana how are you?\nHana: I'm fine thank you. How are you?\nDaniel: I'm fine thanks. So tell me, do you have any plans for the weekend?\nHana: Yes, I heard it's going to be a really nice day on Saturday, so I'm planning to go to the beach with my friends. The beach is three hours away so we are going to go by car, and we are planning to have a barbecue, and I'm very excited.\nHana: In the evening we're going to have fireworks, so it's going to be very beautiful.\nDaniel: So, are you going to stay over at the beach?\nHana: No, we're going to come back so we'll be home quite late.\nDaniel: So then what are you going to do on Sunday?\nHana: I think I'll be sleeping all morning and probably in the afternoon I'm going to study because I have a maths exam on Monday.\nDaniel: Oh, well, that's a shame. Well, I think I'm going to wish you good luck on your exam.\nHana: Have fun at the beach.\nDaniel: Thank you.",
		"avatarURL"	: "https://i.vimeocdn.com/video/697171781.jpg?mw=700&mh=394",
		"mediaURL"	: ""
	},
	{
		"title"		: "The Family",
		"text"		: "Sarah: John, I've never met your family. Do you have a big family?\nJohn: Yeah, kind of. There are five people in my family, so it's a medium family. I have two brothers, so there are three boys in my family. And there's my mother and my father.\nSarah: How about your father? Do you look like him?\nJohn: Yes, I do. I do look like my father. When he was younger. He had blond hair like me and he has glasses. So do I. My mother has glasses, too. I'm the same height as my father. We are both 180 centimeters tall. My older brother is the same height as me and my father. But my younger brother is shorter than us.\nSarah: Ah.\nJohn: He has blond hair and glasses too, though.\nSarah: Oh. How tall is your younger brother?\nJohn: He's a bit shorter than us. I am not sure but I think he's around 170 centimeters tall.\nSarah: Oh. How about your mom?\nJohn: My mom is short, too. She's the same height as my younger brother.\nSarah: Oh.\nJohn: And my mom has red hair. Her hair is bright red, so my mother has different hair from the rest of my family. There are four people with blond people with blond hair and one person with red hair. But actually, all five of us wear glasses.\nSarah: Oh really?\nJohn: Yeah.\nSarah: So John, you're thin. What about the rest of your family? Are they thin, too?\nJohn: Well, my mother is skinny, too, like me. But my brothers are more like my dad in their body type. They are a little bit more muscular than me. They have big muscles and they're very strong. So they are heavier than me. That's my father. He weighs more than I do. And my brothers are also heavier than me.\nSarah: Oh, sounds like a good-looking family.\nJohn: Thank you.",
		"avatarURL"	: "https://i.vimeocdn.com/video/697171787.jpg?mw=700&mh=394",
		"mediaURL"	: "https://vod-progressive.akamaized.net/exp=1607602435~acl=%2A%2F987973688.mp4%2A~hmac=c3c9d029f28d798a061c862f578750eca1f3caa89fb60700b10aaa13537931e2/vimeo-prod-skyfire-std-us/01/3362/10/266810326/987973688.mp4?download=1&filename=Beginner+%2309+Family+Portrait.mp4"
	},
	{
		"title"		: "Family Appearance",
		"text"		: "Sarah: So John, you told me about me about your family's appearance. What about their personality?\nJohn: Well, all five people in my family have different personalities.\nYeah. My younger brother is really fun. It's great to spend time with him. For example, we usually play video games together. He likes to play racing games or sports games, and also, we play card games or just watching TV. He's so funny.\nNo matter what we're doing, he tells jokes and I love listening to him tell jokes about whatever we're doing at the time. And he's so cheerful and bright. He's always open to new people and new ideas. So I really like spending time with him. He makes me feel cheerful, too when we talk together.\nSarah: That's great. How about your older brother?\nJohn: Well, my older brother, he's a really good guy. He's not so entertaining like my younger brother but he's very smart. He's really serious. He likes to study and read. For example, he likes reading the Greek philosophers. He likes reading about Plato and Socrates. And he's always talking about philosophy. I like that stuff, too. I think it's interesting but he's not very funny.\nSarah: I see. How about your dad?\nJohn: My dad. Let's see, what can I say about my dad's personality? He's a hard worker. He's very devoted to everything he tries. He was raised on a farm so he knows a lot about animals. And now, he has a farm as a hobby. My dad raises horses and chickens. He loves animals and he has so many animals but he doesn't think of them as farm animals, they're his pets and he loves them.\nHe spends everyday outside where no matter what the weather, because he has to take care of his family, which is all of his animals. And he's a really smart guy. Maybe a bit serious at times. His sense of humor is maybe like you can imagine from an old man.\nSarah: I see. How about your mother? What's she like?\nJohn: My mother loves to read horror novels.\nSarah: Really?\nJohn: Yeah, horror books. So she knows a lot of stuff about crime or mysteries or police dramas and lawyers. She loves that stuff. So my mother is very interested in those kind of books and movies and TV shows, too. So she's kind of like a detective. My mother is very smart and enjoys solving puzzles.\nSarah: Wow. It sounds like an interesting family.",
		"avatarURL"	: "https://i.vimeocdn.com/video/697171914.jpg?mw=700&mh=394",
		"mediaURL"	: "https://vod-progressive.akamaized.net/exp=1607601087~acl=%2A%2F987974246.mp4%2A~hmac=5f7217b8a03edca46d82f489212c1cc863f8c3c393830784953034e80c7f0d37/vimeo-prod-skyfire-std-us/01/3362/10/266810427/987974246.mp4?download=1&filename=Beginner+%2310+Family+Personalities.mp4"
	},
]