import * as g                           from '../types/genetics'

export const DNA: g.gene[] = [
	{
		"title"		: "In a pickle",
		"text"		: "Narrator: It was a chilly November evening. William Shakespeare's play The Tempest, full of music, magic and monsters, is being performed for the first time. King James I and the Queen are having dinner while they watch.\nKing James: I do like a good play… mmm… and this meat is delicious - bring me more of that pickle… Mmmm… I love a bit of pickle with my dinner… and a nice glass of wine…\nQueen: Don't you think you've had enough wine, dear?\nKing James: Oh do be quiet dear: I can't hear the actors. Now, Mr Shakespeare, is that a King I see on the stage?\nWill: Your Majesty, that is King Alonso of Naples. He is lost on a magical island.\nKing James: And who is this fellow in the jester's costume?\nWill: Your Majesty, that is Trinculo. He drinks a lot, and plans to murder people.\nKing James: A drunken jester? Murder? No good will come of it… does the King know about this?\nWill: Yes, your Majesty. Now, the King is going to find Trinculo - in a drunken mess. Your Majesty might care to listen…\nKing James 1: Ooh yes, yes, I want to hear this, be quiet everybody.\nAlonso: How camest thou in this pickle?\nRobert Harley as Trinculo: I have been in such a pickle since I saw you last that, I fear me, will never out of my bones: I shall not fear fly-blowing.\nKing James 1: Hahaha! He's in a pickle! I like it, Will, very good, very good!\nNarrator: We'll leave them there for now. Pickles are a very messy food, made from fruit and vegetables, crushed and preserved in vinegar and spices - sometimes with alcohol too. When Trinculo says he is in a pickle, he's probably saying that he is very drunk - but he's also got himself into a mess - a very difficult situation. Nowadays, when someone has drunk a lot of alcohol, they can say: I'm pickled - and when they've got problems, they can say: I'm in a pickle. Take The Hunger Games actor Liam Hemsworth, who said:\nClip 1: Most of the time if I'm in a pickle I'll call one of my brothers. They've usually got somewhat uplifting advice.\nClip 2: Ooh, you're in a pickle with those bags aren't you? Let me help.\nKing James I: Now Mr Shakespeare, sit down and eat with us. Have some cold meat!\nServant: Anything with that?\nWill: Hmmm… To pickle, or not to pickle: that is the question.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/1248xn/p03mwdn4.jpg",
		"mediaURL"	: "http://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_in_a_pickle_download.mp3"
	},
	{
		"title"		: "As dead as a doornail",
		"text"		: "Narrator: It was a cold morning. William Shakespeare is in the theatre, working on Henry VI part II, whilst his actor friend Thomas Swann is mending a broken door.\nWill: Thomas! Can you stop that banging? I'm trying to write here!\nThomas: Will, this door needs fixing properly. I have to hit this doornail hard… there. That will never come out.\nWill: What's that about a doornail? Hmmm… you've just given me an idea… dead as a doornail… dead as a doornail!\nThomas: Who's dead?! Will?\nWill: Thomas, I have the perfect line for your character… Jack Cade, the rebel leader, strong and proud. But in this scene, he's on the run, hiding from his enemies. He hasn't eaten anything for five days, except herbs… even grass… he's weak… alone… and suddenly, six of his enemies find him.\nThomas: So he's in danger…\nWill: Yes, but he doesn't show any fear: in fact, he threatens to kill all of them dead as a doornail. Come Thomas, let's read your lines. Look on me well: I have eat no meat…\nThomas as Jack Cade: Look on me well: I have eat no meat these five days; yet come thou and thy five men, and if I do not leave you all as dead as a doornail, I pray God I may never eat grass more.\nWill: You have it! Well done Thomas: there's another classic Shakespeare line.\nThomas: I don't know how you do it, Will.\nNarrator: We'll leave them there for now. The phrase as dead as a doornail was in common use in Shakespeare's day. It means the same today as it did back then: Dead. Very dead. Totally dead. It's a very well-known English expression - for example, novelist Charles Dickens used it to describe the character Marley in A Christmas Carol:\nClip 1: Old Marley was as dead as a doornail.\nNarrator: These days we can use it for electrical gadgets that aren't working.\nClip 2: Oh no - I forgot to charge my phone. It's as dead as a doornail.\nWill: Right! All that writing has made me thirsty. Let us go to the Duck and Whistle. Come on Thomas, close the door behind you… Hmmm… perhaps you should put another couple of nails in that door before we go, Thomas?\nThomas: Ahh… To nail, or not to nail: that is the question.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/1248xn/p03g77bn.jpg",
		"mediaURL"	: ""
	},
]


// {
// 	"title"		: "",
// 	"text"		: "",
// 	"avatarURL"	: "",
// 	"mediaURL"	: ""
// },