import * as g                           from '../types/genetics'

export const ABC: g.snapMargin = [] as any; 
export const DNA: g.gene[] = [
	{
		"title": "1. New to America",
		"text": "Nancy was new to America. She came to America speaking only her native language. She brought her 8-year-old son with her. He was all she had in the world. They found an apartment in Arcadia. They were there for only two months when a neighbor’s dog jumped over the fence. The dog ran toward Nancy’s son. Nancy put her body in between the dog and her son. The dog stopped when it saw Nancy screaming at it. She was going to punch it in the nose. The dog turned around. Shaking, Nancy took her son upstairs. They stayed in the apartment all weekend. Then Nancy found another apartment, close to the school that her son was going to attend. She and her son walked everywhere. One day her son started coughing badly. He had an asthma attack. All the walking was making his asthma worse. Nancy knew that she had to buy a car. So she called up the Honda dealer. She talked to a salesman who spoke her language. She told him that she wanted to buy a new car if he could come over to pick her up. The salesman said he would be right over. ",
		"avatarURL": "https://static.lingq.com/media/resources/contents/images/2013/06/08/6e754849aa.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/08/New_to_America_.e0b7a57d2f95.mp3"
	},
	{
		"title": "2. A Haircut",
		"text": "It was time for a haircut. Lenny didn’t even have to look in the mirror. Even though he was going bald, he knew that he needed to cut his hair every two weeks. He had a \"tongue\" of hair on the top of his head. His hair was thinning at the crown. He still had plenty of hair on the sides and back. It was what they call \"salt and pepper,\" a mixture of gray hair and dark brown hair. It was only a few years, he figured, until the salt and pepper became just salt. He never let his hair grow for more than two weeks. The longer it got, the worse it looked, he thought. He spread a newspaper over the bathroom sink so that no hair went down the drain. He plugged in the clippers and started cutting his hair. He started at the back of his head, went to the sides, and finished on the top. Every minute or so, he had to clean the hair out of the blades with an old toothbrush. Finished, he picked up a hand mirror to check out the back of his head. Everything looked okay. He carried the newspaper back out to the kitchen and shook the hair clippings into the trash can. Then he took a shower. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/08/A_Haircut_VCZo.e5a5a3200ddc.mp3"
	},
	{
		"title": "3. The Yardman",
		"text": "The yardman comes every two weeks. He drives a gray pickup truck. The truck is a Ford. It is about 15 years old, but it runs well. It doesn’t burn oil, and it gets decent gas mileage. The yardman’s name is Byron. In the back of his truck are a lawn mower, a leaf blower, a rake, and a shovel. Byron uses the leaf blower to blow leaves and dirt from the back of the building out to the front of the building. Then he rakes up the leaves into a bag. He blows the dirt out into the street. He cuts the lawn with his lawn mower. He trims the hedge. He uses the leaf blower to blow the dirt off each Welcome mat that lies in front of each apartment door. Then he puts all the leaves, the grass trimmings, and the hedge clippings into a wheelbarrow. He pushes the wheelbarrow to the back of the building, where he uses his big shovel to empty the wheelbarrow contents into the big dumpster. It takes Byron about two hours to do this work. When he is done, he goes half a block up the street to the house on the corner. There he does the same work again. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/08/Yardman_Vayn.a342bb0fec91.mp3"
	},
	{
		"title": "4. Grab Your Umbrellas",
		"text": "It looked like rain. The sky was gray. It was almost noon, but the sun was hidden by a gray blanket. It was cool. There were no birds flying anywhere. A couple of birds sat on the telephone wire. Bob was standing outside talking to Bill. They both had their hands in their pockets. They knew that it was probably going to rain shortly. A sudden breeze blew some leaves off a tree onto the sidewalk. A young woman wearing a dark blue coat and jeans walked by. She was walking a small dog. It was pure white, and pretty. It sniffed at a tree trunk. The woman waited patiently. Finally, the dog lifted its leg. Bob said that he liked the rain. It was a nice change from the usual hot Los Angeles weather. And the plants could always use the extra water. Bill said the only thing he didn’t like about rain was that all the motor oil on the streets would get washed into the ocean, and so would all the trash. \"But that never stops the surfers,\" Bob said. \"They don’t seem to care what’s in the water, as long as there are waves to surf on.\" ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/09/Grab_Your_Umbre.b019d59a0f2e.mp3"
	},
	{
		"title": "5. Shopping for Bargains",
		"text": "Jim went to the thrift shop. He wasn’t looking for anything in particular. He liked to go there just to browse. A big sign on the front door said OPEN. The shop was closed on Sunday and Monday. The rest of the week, it opened at 10 a.m. and closed at 2 p.m. Two women worked inside. They rang up sales and put the items into plastic bags for the customers to carry out. At the back of the shop was a big room where another lady worked. She sorted the new donations and put price tags on them. At the end of each day, she would bring the new donations out to the main part of the shop. Everyone who worked at the thrift shop was a volunteer. The only \"payment\" they received was that they had the opportunity to see, and buy, any items in the shop before the customers did. When Jim entered, the lady at the register told him hello. He smiled and said hello. She knew Jim because he was a regular customer. Jim said, \"What’s new?\" She laughed and said that nothing was ever new at a thrift shop. \"It’s always old and it’s always used,\" she smiled. Jim looked at the watches in the glass case. He saw one that he liked. \"Could I look at that one?\" he asked. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/09/Shopping_for_Ba.51009483a6e5.mp3"
	},
	{
		"title": "6. Horses to Ride",
		"text": "Laura went to the stable. Four horses stood there. She put a saddle on Star. He was seven years old, big and dark brown. Her sister came out to the stable. They were both going to exercise the horses. It was a warm, sunny day. Janice saddled up Moonbeam, a white mare. They got on the horses and started walking them. A few minutes later, Laura was telling Janice about the new doctor in her hospital. She raised her hand for a second to make a point. Just then, Star bucked. Laura went flying into the air. She landed on her head and shoulder on the grass. \"Oh, my gosh!\" Jan cried. \"Laura, are you all right?\" Laura moaned. Jan gently rolled her over. She didn’t see any blood. That’s good, she thought. \"Can you move? You’re not paralyzed anywhere, are you?\" Jan pulled Laura up into a sitting position. Laura slightly moved her legs and arms. She wasn’t paralyzed. When she moved her right hand to touch her head, she groaned. \"What’s the matter?\" \"That hurt. When I moved my arm, it hurt.\" They still didn’t see any blood. Jan unbuttoned the top buttons on Laura’s blouse and looked at Laura’s right collarbone. \"Oh, no,\" she said. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/09/Horses_to_Ride_.55717cf53524.mp3"
	},
	{
		"title": "7. Garlic Powder",
		"text": "Mike looked at the label on the big plastic container. It said Garlic Powder. There was a U with a circle around it after the word Powder. What does this U mean, Mike wondered. Under the word Powder was another word, Seasoning. Under that word was a drawing of a garlic bulb. Mike knew that food labels can be tricky. Powder is powder, but Seasoning could mean salt. He looked all around the plastic container for an ingredients label. There wasn’t one. In small print under the drawing of the garlic bulb was a phone number: 1-800-632-6900. Call that number if you have comments or questions, the label said. Mike called the number. A woman answered. He asked her what the U inside a circle meant. She said it meant kosher. Kosher food is food that is prepared according to Jewish law. Mike asked where the ingredients label was. She said if there is only one ingredient, there is no ingredients label. \"So, there is no salt in this product?\" Mike asked. \"No, sir,\" she said. \"It’s 100 percent garlic powder.\" \"Why does it say, Product of USA and China?\" She said that sometimes they get the garlic from China, sometimes they get it from the US. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/09/Garlic_Powder_O.4846ac85a87d.mp3"
	},
	{
		"title": "8. A Shower Injury",
		"text": "Ben leaned over the edge of the tub. He turned on the hot and cold water faucets. The water came out of the spout near the top of the tub. He pushed down on the lever beneath the spout so that the water would drain. He was going to take a shower, not a bath. He tested the temperature. It wasn’t hot enough. He adjusted the hot water faucet. There was another handle between the hot and cold faucets. This one controlled whether water came out of the spout or out of the shower head. Ben turned it all the way to the right. Now hot water was coming out of the shower head. The temperature was just right. Ben took off his robe and stepped over the top of the tub. He pulled the shower door closed. He grabbed the bar of soap out of the soap dish and started scrubbing his face. While his eyes were closed to keep out the soap, he put the soap back into the dish. Then he reached for the big plastic container of shampoo on his window ledge. The bottle slipped out of his hands and landed on his left foot. \"Shoot!\" Ben said angrily. That hurt. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/09/A_Shower_Injury.ec27876ba112.mp3"
	},
	{
		"title": "9. Pete's Sharp Knife",
		"text": "Pete was in his kitchen. He was about to slice three green apples. He liked to eat fresh apples with cinnamon sprinkled on them. He opened the blinds so that he could get more sunlight into the kitchen. Now he could see what he was doing. He grabbed a knife out of a drawer. It said \"Surgical Stainless USA\" on the side of the blade. The blade was very thin and light. It had teeth, like a saw. The handle was a brown piece of cheap hollow plastic. He had bought this knife about 20 years ago at a county fair. It was one of those knives that were advertised on TV. It could cut through a tomato can, and then cut easily and cleanly through a fresh tomato. \"You never need to sharpen it. The sharp edge is guaranteed for life.\" That's how they advertised it. And Pete, for once, couldn't argue that the advertisers lied. This was a great knife. But it was also a dangerous knife. A couple of years ago, Pete was careless. He was rapidly slicing a potato and the blade got his finger. The doctor put three stitches in Pete's finger. \"Next time, be more careful,\" the doctor said. No kidding, Pete thought. He was so careful that he didn't use the knife for almost a year. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/09/Petes_Sharp_Kn.de62f0cb08e5.mp3"
	},
	{
		"title": "10. Provider Overbills Customer",
		"text": "Simon got a monthly bill that he didn’t like. His Internet service provider, Wink, automatically withdrew $15 from his checking account each month. This was called direct payment. It made things simpler for him because it meant one less check to write each month. In fact, Simon had direct payments with his gas company, his phone company, and his electric company. So that was four fewer checks that he had to write each month. This month, instead of $15, Wink had withdrawn $75. Simon went online and looked at his account. Part of the increase was because he had switched from a slow dial-up connection to a fast DSL connection. Wink charged him $45 just to make that switch. Simon thought that this charge in itself was ridiculous. It probably took them about five seconds to make the switch. But any time a corporation can gouge you, they will. In addition to the $45, Wink had charged him $15 for his dial-up account, but had also charged him $15 for his DSL account. This was a double-charge, since a computer uses dial-up or DSL, but not both. We’ll see about this, Simon thought, as he searched for Wink’s 800 number. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/09/Provider_Overbi.3ae44821838e.mp3"
	},
	{
		"title": "11. A Good Sandwich",
		"text": "Gordon was hungry. He opened the refrigerator. There must be something in here to eat, he thought. There was—a single hot dog. He took it out of its package and put a small frying pan onto the stove’s gas burner. He turned on the heat. Then he poured a little bit of vegetable oil into the pan. He sliced the hot dog in half lengthwise. When the oil got hot, he put the two halves in the pan. About a minute later, he flipped each half over. After another minute, he took the hot dog out of the pan. Gordon put two slices of bread into the toaster. This was tasty and healthy bread. The first ingredient listed was organic sprouted wheat. The first ingredient in ordinary bread is usually unbleached flour. When the toast popped up, he put mustard, mayonnaise, and ketchup on one slice. Then he added two slices of onion. On top of the onions, he placed the hot dog. On top of the hot dog, he put a couple of slices of apple. Then he added some bits of hot green chile, and then put the top piece of toast onto the chile bits. Ahh, what a sandwich, he thought, as he sat down to eat. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/10/Good_Sandwich_n.e7215633b28f.mp3"
	},
	{
		"title": "12. Sara's Upset Stomach",
		"text": "Sara needed to see the doctor. She had an upset stomach. She felt bloated, and needed to pass gas every minute or so. This was terrible. She couldn’t go anywhere in public. Her friends told her it was because she had moved to America. The air, water, and food in America weren’t agreeing with her. They said she would have to return to her home country. \"No way,\" Sara said. She didn’t want to go home. She liked America. This was a minor problem, she was sure. Any good doctor would solve it in no time. Two days later, she saw her doctor. He asked her if she drank milk. She said yes, three glasses a day. \"Don’t drink any more regular milk. Start drinking lactose-free milk, because lactose can upset your stomach.\" Then he asked her if there were any big problems in her life. She said that her boyfriend was a big problem. He wanted to get married, but she didn’t. The doctor said that she should find another boyfriend. \"Why?\" Sara asked. \"Because your boyfriend is giving you too much stress. He is probably the main cause of your upset stomach.\" \"I don’t think my boyfriend is going to like that.\" \"Just tell him if he really loves you, he should leave you.\" ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/10/Saras_Upset_St.82f0b61223d2.mp3"
	},
	{
		"title": "13. Please Marry Me!",
		"text": "Jill answered the phone. It was Jack. \"Jill, will you marry me next week?\" \"What?\" Jack repeated his question. \"Of course not,\" she replied. She wondered why he was asking her that question. They had already agreed that when people get married, they immediately start to take each other for granted. They don’t do the \"little things\" like opening the car door or holding hands. They get too comfortable. They treat their partner like an old shoe. And eventually, they get bored with each other and get divorced. \"We already agreed that we don’t want to get married because we don’t want to get divorced.\" Jack agreed. But he argued that they were special. They were different from other couples. They loved each other too much to end up in a divorce. \"Yes, that may be true. But still, why next week? Why can’t we think about it for another year or two?\" \"Because I had two dreams the last two nights. In both dreams, you left me for another man. In fact, you left me for two different men. I want to get married now so I don’t have these dreams anymore.\" \"Hmm. What did these men look like?\" ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/10/Please_Marry_Me.867138fcc87e.mp3"
	},
	{
		"title": "14. Laundry Day",
		"text": "Saturday morning meant one thing for Susan—doing the laundry. She hated doing the laundry. Unenthusiastically, she took the pillow cases off all the pillows. Then she removed the fitted sheet from the mattress. She took the towel off the towel bar in the bathroom. She grabbed a couple of dirty dish towels out of the kitchen, and looked all around her apartment for anything else that needed washing. In the corner of her living room, a can of coins sat on top of the file cabinet. She fished out seven quarters. She opened the cabinet under her kitchen sink and grabbed a plastic bottle of liquid detergent. Finally, she set her electronic timer for 35 minutes. The timer would remind her that the washing was done, and that it was time to go back downstairs and put the clothes into the dryer for 40 minutes. Without the timer, Susan would completely forget to check her clothes. Susan carried the laundry basket downstairs. How happy she would be when her laundry was done for this week. As she approached the laundry room, she heard a familiar sound. The sound was the washer washing and the dryer drying. One of her neighbors had got there before her. Muttering, Susan took her basket back upstairs. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/10/Laundry_Day_Z22.efde5ddab711.mp3"
	},
	{
		"title": "15. A Noisy Neighbor",
		"text": "Barbara couldn’t take it any more. Her upstairs neighbor was blasting his stereo again. She had asked him twice already to turn the volume down. The first time she asked, he was surprised. He said he didn’t know that she could hear his stereo. \"Yes,\" she said, \"it’s just like your stereo was in my living room. I can hear every note!\" He said he would keep it down. She hoped that he was telling the truth. Of course, he wasn’t. The very next day, he blasted his stereo. She marched upstairs to remind him of his promise. He said the volume was so low that he could barely hear it. She asked him to turn it lower. He said he would try. Barbara could swear that when she reentered her apartment, the music was louder than when she had walked upstairs. So, this was the third time. She took her baseball bat upstairs with her. She knocked very loudly on his door. When he opened the door, she screamed at him like a crazy person. She told him she would kill him if he didn’t turn the music down and keep it down. His eyes got big. She went back downstairs. She couldn’t hear a note. I can’t believe I said that, she told herself. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/10/A_Noisy_Neighbo.18c247fa6439.mp3"
	},
	{
		"title": "16. The New Realtor",
		"text": "Norma was discouraged. She was a new realtor. She had recently passed the state test on her first try. Then she joined a realty company. They offered training classes two to four times a week. Norma attended the classes faithfully. But because English was her second language, she didn’t catch everything that the instructor said. When she asked the instructor to repeat something, he told her to see him after class. But when other students asked a question, the instructor answered the question right then and there. To Norma, the instructor always said, \"See me after class.\" Then, when she tried to see him after class, he would say that he was late for an appointment. \"How about next time?\" he would say. He was always too busy to help her. \"He’s not too busy, he’s just too lazy,\" her boyfriend said. \"There are too many 'instructors' like that. All they care about is presenting their information. If the students don’t get it, that’s their problem. You have to be strong. These people are not going to help you. They want you to fail, because that means less competition for them. It’s a dog-eat-dog business.\" ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/11/The_New_Realtor.95b039b0705a.mp3"
	},
	{
		"title": "17. The Fire Alarm",
		"text": "Jennifer’s ears were \"talking\" to her. They were making little sounds, like little bubbles bursting. A \"bubble\" was bursting almost every second. It was not painful, but annoying. She knew the cause. While she was cleaning the whiteboard after her class ended last night, the fire alarm went off. Instead of leaving the building immediately, she walked around to see what the problem was. The blaring alarm sounded like the busy signal on a phone, but 1,000 times louder. The school seemed to be empty. Then she walked by one room, and saw about seven students inside. Just then the night supervisor came by. She told everyone to leave immediately. The students were packing their hair-care equipment into their bags. The night supervisor waited impatiently. Finally, after almost five minutes, all the students and their teacher left the building. They apologized for being so slow. The firemen never arrived. Instead, a school police officer showed up. He walked around the area with the supervisor. It was a false alarm. The officer used his key to finally turn off the alarm. But it was too late for Jennifer. She had listened to the loud alarm for too long. She should have known better. Even as she drove home, her ears felt strange. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/11/ns017_YG6f.73740c40673f.mp3"
	},
	{
		"title": "18. Eddie's Short Visit",
		"text": "Eddie drove over to see Betty. When he got to her apartment at about 3:15 p.m., he saw that her car wasn’t in the carport. So he wrote a note: \"Hi, Betty. I love you and I miss you. Love, Eddie.\" He was about to tape the note onto her front door when he saw her car pull up. She walked up the stairs. Instead of the big smile, hug, and kiss that she usually greeted him with, she simply said, \"What’s up?\" \"You didn’t call me back for the last two days, honey, so I came over to see you.\" He gave her the note. She opened it, read it, and put it on the kitchen table. \"That’s sweet,\" she said. She walked into her bedroom. Eddie followed her. She put her purse on the bed. Eddie tried to hug her. \"I have to wash my hands,\" she said. When she came out of the bathroom, she told Eddie that he should go home. She said that she was hungry and tired. She was going to fix something to eat. Then she was going to take a nap. She said that she might call him later. During Eddie’s entire five-minute visit, Betty had constantly avoided his eyes. Instead of walking him out to his car, like she usually did, Betty locked her front door as soon as Eddie was outside her apartment. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/11/ns018_k18B.90166012befa.mp3"
	},
	{
		"title": "19. Carbon Monoxide",
		"text": "Helen stepped outside her front door to see what the weather was like. It was sunny and warm. That was nice, because for the past two weeks it had been cold and rainy. It had been so cold that she had had to turn her heater on. She was lucky, because her heater worked and she could pay her heating bills. Some people in Los Angeles were not so lucky. Unable to use their home heater, they placed charcoal into a barbecue grill and lit it. The heat kept them warm, but the carbon monoxide killed them. This happens almost every winter in Los Angeles. People shut all the windows tight to keep the cold out, then light the charcoal. Soon enough, the oxygen in their home is consumed by the open flames. The family suffocates to death. Everyone knows that smoke detectors are required in Los Angeles. But many people don’t know about, or don’t think they need, carbon monoxide detectors. They’re not expensive. A $25 investment can save a family from death. People always think that nothing bad will happen to them; it always happens to \"the other guy.\" So they forget to put fresh batteries into their smoke detectors annually, and they don’t bother to buy carbon monoxide detectors. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/11/ns019_AGCL.f8edc41d78e4.mp3"
	},
	{
		"title": "20. A Visit to Asia",
		"text": "Liz was excited. She was going to Asia with her mom. Neither of them had ever traveled out of the United States before. They were going to fly to Hong Kong. After staying in Hong Kong for three nights, they would travel on their cruise ship to Shanghai and Beijing. \"Beijing is inland, so we have to take about a two-hour bus ride to get there from the port. I forget the name of the port. Anyway, we’re going to see the Great Wall, the Tiananmen Square, and the Forbidden City. It’s going to be so cool!\" she told her neighbor Jane. From China, the cruise ship would go to Pusan in South Korea, and finally to Tokyo. From Tokyo, they would catch a flight back to Los Angeles. \"The trip is going to last three weeks. It’s only going to cost us $2,800 each, IF we can control our urge to shop,\" she laughed. \"I hope your trip is more fun than mine was,\" said Jane. \"I took a cruise to the Bahamas, but almost all the passengers got sick. I caught some kind of virus that made me throw up for almost three days. They gave us a discount that we could use on a future trip. Ha! No more cruising for me.\" \"We’ve heard about those disasters,\" said Liz. \"Mom and I are going to be washing our hands every 30 minutes, and we’re bringing surgical masks with us.\" ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/11/ns020_Ja2f.d178444450.mp3"
	},
	{
		"title": "21. School Boys",
		"text": "Jerome turned off the TV. He had just watched a couple of \"South Park\" cartoons. \"South Park\" is an amusing series about elementary school kids living in a small town in Colorado. The first cartoon was about Herman, who wanted to become strong and muscular. He asked his mother to buy a supplement that was advertised on TV. The supplement was actually nothing but sugar, but the TV ad promised that it would make you strong and muscular. Instead, it made Herman very fat. Worse, Herman refused to believe that he had become fat. Even though all his friends were calling him Super Fat Boy, he told them that he was Super Muscle Boy. Finally, when Herman walked onto the stage to receive an award in the school auditorium, the stage collapsed. Then he realized that maybe he WAS super fat. The second cartoon was about a dog that followed Lenny home. Lenny loved the dog until he found out it was gay. Then he hated the dog. But Big Al took Lenny to the city’s Home for Gay Animals. While there, Lenny decided that it was okay to be gay. When he got home, he hugged his dog and took it for a walk. He didn’t even mind when it sniffed other male dogs. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/11/ns021_WYJY.9fbb6e82b688.mp3"
	},
	{
		"title": "22. The Loose Button",
		"text": "George wore a pair of blue shorts around the house. They were old, faded, and ugly, but they were comfortable. And when you are at home, you want to be comfortable. It wouldn’t be called \"Home, Sweet Home\" if you didn’t feel comfortable there. But when he put on his blue shorts one morning, the button was just hanging on by a thread. That single button was the only thing that held his shorts up. George could do two things. He could wait until the button fell off. When that happened, it would probably roll under the sofa and be lost forever. Or, he could sew the button on securely before it fell off. He found his sewing kit. He threaded the needle and tied a knot at the end of the thread. Then he started the needle through the cloth. He directed it through one of the holes in the button. Then he reversed direction. He put the needle back through a different hole, and then through the cloth again. He repeated this motion through all four button holes until the button was tight. Then he tied a bunch of knots in the last bit of thread and snipped off the excess thread. He put on the shorts and buttoned the button. It was strong. Good for another ten years, he smiled to himself. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/11/ns022_jCoF.7e02cb978180.mp3"
	},
	{
		"title": "23. The Pile of Paper",
		"text": "Sammy looked at the pile of paper on the floor. Whenever he finished reading his mail or a newspaper or magazine, he threw it into this pile. This was his recycling pile. At the moment, it was almost two feet high. It was time to recycle. He squatted down, protecting his back. Sometimes, just sitting down would cause his back to go out for a week. He scooped his hands under the pile and slowly stood up. He walked over to his front door. Hands full, he struggled to turn the doorknob and open the door. He walked outside and down the stairs. So far he hadn’t dropped one piece of paper. He walked to the blue trash bin. There was no way to lift the lid of the recycling bin with his hands full. He carefully put the pile of papers down and then opened the lid. The bin was completely full. Damn, he swore. Sammy gathered the pile into his arms and trudged back upstairs. Pleased that he still had not dropped any paper, he lowered the pile back onto the floor. Then he stood up, but just a little bit too fast. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/11/ns023_oJhU.ea72fb0293bd.mp3"
	},
	{
		"title": "24. Brushing and Flossing",
		"text": "Kevin had just finished dessert. It was a piece of dark chocolate, washed down with a glass of cold milk. Delicious! He rinsed his mouth out with a glass of water, and then spit into the kitchen sink. He sat down at the dining room table and grabbed some floss. He carefully flossed his top teeth and then his bottom teeth. Flossing was a chore. The floss almost always got stuck between two teeth in the upper back and two teeth in the lower front. Finally finished, he threw the frayed floss into the trash. He went into the bathroom and grabbed his electric toothbrush. TV ads always show people putting toothpaste onto the entire length of the brush. Of course, that was to get them to use up the tube faster so they’d have to buy another tube sooner. Kevin put just a little toothpaste onto the brush. He brushed for about a minute. He spent another 30 seconds brushing his tongue. Then he spit out all the toothpaste, and gargled and spit again. Brushing and flossing are such a pain, he thought. If they can put a man on the moon, why can’t they invent something easier and faster than toothpaste and dental floss? ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/11/ns024_aepN.f8ec6782782c.mp3"
	},
	{
		"title": "25. Raising the Kids",
		"text": "Louise and Neil had been dating for three years. She was 40, and he was 50. They wanted to get married and have two kids as soon as possible, but there was a problem. They disagreed on how they would raise their kids. Because Louise had a high-paying job, Neil could stay home and raise the kids. He looked forward to that, because he felt that he would be a great dad. First, he would teach them how to read. Then he would teach them about life. His kids were not going to waste their time reading fairy tales and watching Sesame Street. They were going to learn practical stuff, like how to use Microsoft Office and how to get a four-year scholarship to Harvard. He wanted them to become business majors, because business is where the money is. Louise had other plans. She wanted her kids to relax and enjoy life. She didn’t want them to grow up too fast. She was the oldest child in a poor family, and her father had put her to work in the fields as soon as she turned six. Life had been hard for her. She didn’t want it to be hard for her children. Neil said not to worry. There was still plenty of time for him to figure out a way for the kids to have fun and still become happy millionaires. ",
		"avatarURL": "https://static.lingq.com/media/resources/collections/images/2013/06/08/14525a7da3.jpg",
		"mediaURL": "https://s3.amazonaws.com/media.lingq.com/resources/contents/audionorm/resources/contents/audio/2013/06/11/ns025_3G7o.f4814dab6aeb.mp3"
	}
];